version: '3.8'

services:
  api:
    build: .
    image: hotel-cancellation-prediction:latest
    container_name: hotel-cancellation-api
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-file:./mlruns}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MODEL_TYPE=${MODEL_TYPE:-xgboost}
    env_file:
      - .env
    volumes:
      - ./models:/app/models:ro
      - ./mlruns:/app/mlruns:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-ui
    ports:
      - "${MLFLOW_UI_PORT:-5001}:5000"
    volumes:
      - ./mlruns:/mlruns
    env_file:
      - .env
    command: mlflow ui --host 0.0.0.0 --backend-store-uri file:///mlruns
    restart: unless-stopped
